name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version:  1.21.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run unit tests and generate the coverage report
        run: make test-race

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.2

      - name: Install revive linter
        run: go install github.com/mgechev/revive@v1.1.3

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
  
      - name: Lint
        run: make lint
      
      - name: Fmt
        run: make fmt
